---

version: '3'
services:
  yeti:
    build:
      context: ../../
      dockerfile: ./extras/docker/Dockerfile
    image: yeti-platform
    ports:
      - "5000:5000"
    links:
      - redis
      - mongodb
    restart: always
  redis:
    image: redis:latest
  mongodb:
    image: mongo:4.0.12
    environment:
      - MONGO_LOG_DIR=/dev/null
    command: mongod
